import os
from dotenv import load_dotenv
from telegram import ReplyKeyboardMarkup, ReplyKeyboardRemove, Update
from telegram.ext import (
    Application,
    ApplicationBuilder,
    CommandHandler,
    MessageHandler,
    ConversationHandler,
    ContextTypes,
    filters,
)

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN")

# States
(
    CHOICE,
    TOTAL,
    PEOPLE_EQUAL,
    PEOPLE_INDIV,
    NAME_INDIV,
    ITEM_COUNT,
    ITEM_AMOUNT,
    GST_INDIV,
    SERVICE_INDIV,
) = range(9)


def format_money(amount: float) -> str:
    return f"${amount:.2f}"


def build_summary(context_data: dict) -> str:
    """Build a shareable plain-text bill summary."""
    lines = ["🧾 *Bill Summary*", ""]

    split_type = context_data.get("split_type")
    gst = context_data.get("gst", 0)
    service = context_data.get("service", 0)

    if split_type == "equal":
        total = context_data["total"]
        people = context_data["people"]
        per_person = total / people

        lines += [
            f"Split: Equal among {people} people",
            f"Total bill: {format_money(total)}",
            "",
            f"💰 Each person pays: *{format_money(per_person)}*",
        ]

    else:  # individual
        names = context_data["names"]
        amounts_by_person = context_data["amounts_by_person"]
        base_total = sum(sum(v) for v in amounts_by_person.values())
        service_amount = round(base_total * (service / 100), 2)
        subtotal = base_total + service_amount
        gst_amount = round(subtotal * (gst / 100), 2)
        grand_total = subtotal + gst_amount

        lines += [
            "Split: Individual",
            f"Base total: {format_money(base_total)}",
            f"Service charge ({service:.2f}%): {format_money(service_amount)}",
            f"GST ({gst:.2f}%): {format_money(gst_amount)}",
            f"Grand total: {format_money(grand_total)}",
            "",
            "💰 Per person:",
        ]

        for name in names:
            person_items = amounts_by_person.get(name, [])
            person_base = sum(person_items)
            if base_total == 0:
                final_share = 0.0
            else:
                final_share = grand_total * (person_base / base_total)

            item_detail = ""
            if len(person_items) > 1:
                item_strs = " + ".join(format_money(a) for a in person_items)
                item_detail = f" ({item_strs})"

            lines.append(
                f"  *{name}*: base {format_money(person_base)}{item_detail} → *{format_money(final_share)}*"
            )

    lines += ["", "─────────────────────"]
    lines.append("Generated by @Keikie\\_Bot")
    return "\n".join(lines)


# ──────────────────────────────────────────────
# /start
# ──────────────────────────────────────────────

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(
        "👋 Hello! I can help split a bill.\nSend /split to begin."
    )


# ──────────────────────────────────────────────
# Conversation entry
# ──────────────────────────────────────────────

async def split_start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    context.user_data.clear()
    keyboard = [["Equal", "Individual"]]
    reply_markup = ReplyKeyboardMarkup(keyboard, resize_keyboard=True, one_time_keyboard=True)
    await update.message.reply_text(
        "Do you want to split the bill equally or by individual amounts?",
        reply_markup=reply_markup,
    )
    return CHOICE


async def choose_split_type(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    choice = update.message.text.strip().lower()
    if choice == "equal":
        context.user_data["split_type"] = "equal"
        await update.message.reply_text("Send me the total bill amount.", reply_markup=ReplyKeyboardRemove())
        return TOTAL
    if choice == "individual":
        context.user_data["split_type"] = "individual"
        await update.message.reply_text("How many people are splitting the bill?", reply_markup=ReplyKeyboardRemove())
        return PEOPLE_INDIV
    await update.message.reply_text("Please choose either Equal or Individual.")
    return CHOICE


# ──────────────────────────────────────────────
# Equal split flow (no GST/service — total is the final receipt amount)
# ──────────────────────────────────────────────

async def get_total(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    try:
        total = float(update.message.text.strip())
        if total <= 0:
            raise ValueError
    except ValueError:
        await update.message.reply_text("Please enter a valid positive number for the total bill.")
        return TOTAL
    context.user_data["total"] = total
    await update.message.reply_text("How many people are splitting the bill?")
    return PEOPLE_EQUAL


async def get_people_equal(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    try:
        people = int(update.message.text.strip())
        if people <= 0:
            raise ValueError
    except ValueError:
        await update.message.reply_text("Please enter a valid whole number greater than 0.")
        return PEOPLE_EQUAL
    context.user_data["people"] = people

    summary = build_summary(context.user_data)
    await update.message.reply_text(summary, parse_mode="Markdown")
    await update.message.reply_text("📋 You can copy the summary above and share it with your group!")
    return ConversationHandler.END


# ──────────────────────────────────────────────
# Individual split flow
# ──────────────────────────────────────────────

async def get_people_individual(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    try:
        people = int(update.message.text.strip())
        if people <= 0:
            raise ValueError
    except ValueError:
        await update.message.reply_text("Please enter a valid whole number greater than 0.")
        return PEOPLE_INDIV
    context.user_data["people"] = people
    context.user_data["names"] = []
    context.user_data["amounts_by_person"] = {}
    context.user_data["current_person_index"] = 0
    await update.message.reply_text("What's the name of Person 1?")
    return NAME_INDIV


async def get_name_individual(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    name = update.message.text.strip()
    if not name:
        await update.message.reply_text("Please enter a valid name.")
        return NAME_INDIV

    context.user_data["names"].append(name)
    context.user_data["amounts_by_person"][name] = []
    context.user_data["current_name"] = name

    await update.message.reply_text(
        f"How many items did *{name}* order? (Enter a number, e.g. 2)",
        parse_mode="Markdown",
    )
    return ITEM_COUNT


async def get_item_count(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    try:
        count = int(update.message.text.strip())
        if count <= 0:
            raise ValueError
    except ValueError:
        await update.message.reply_text("Please enter a valid number of items (at least 1).")
        return ITEM_COUNT

    name = context.user_data["current_name"]
    context.user_data["item_count"] = count
    context.user_data["current_item"] = 1

    await update.message.reply_text(
        f"Enter the amount for *{name}*'s item 1 of {count}:",
        parse_mode="Markdown",
    )
    return ITEM_AMOUNT


async def get_individual_amount(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    try:
        amount = float(update.message.text.strip())
        if amount < 0:
            raise ValueError
    except ValueError:
        name = context.user_data["current_name"]
        item_num = context.user_data["current_item"]
        await update.message.reply_text(f"Please enter a valid amount for {name}'s item {item_num}.")
        return ITEM_AMOUNT

    name = context.user_data["current_name"]
    context.user_data["amounts_by_person"][name].append(amount)

    current_item = context.user_data["current_item"] + 1
    item_count = context.user_data["item_count"]

    if current_item <= item_count:
        context.user_data["current_item"] = current_item
        await update.message.reply_text(
            f"Enter the amount for *{name}*'s item {current_item} of {item_count}:",
            parse_mode="Markdown",
        )
        return ITEM_AMOUNT

    # Move to next person or proceed to GST
    next_index = context.user_data["current_person_index"] + 1
    context.user_data["current_person_index"] = next_index
    people = context.user_data["people"]

    if next_index < people:
        person_num = next_index + 1
        await update.message.reply_text(f"What's the name of Person {person_num}?")
        return NAME_INDIV

    await update.message.reply_text("Enter GST percentage (e.g. 9). Send 0 if none.")
    return GST_INDIV


async def get_gst_individual(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    try:
        gst = float(update.message.text.strip())
        if gst < 0:
            raise ValueError
    except ValueError:
        await update.message.reply_text("Please enter a valid GST percentage, like 9 or 0.")
        return GST_INDIV
    context.user_data["gst"] = gst
    await update.message.reply_text("Enter service charge percentage (e.g. 10). Send 0 if none.")
    return SERVICE_INDIV


async def get_service_individual(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    try:
        service = float(update.message.text.strip())
        if service < 0:
            raise ValueError
    except ValueError:
        await update.message.reply_text("Please enter a valid service charge percentage, like 10 or 0.")
        return SERVICE_INDIV
    context.user_data["service"] = service

    summary = build_summary(context.user_data)
    await update.message.reply_text(summary, parse_mode="Markdown")
    await update.message.reply_text("📋 You can copy the summary above and share it with your group!")
    return ConversationHandler.END


# ──────────────────────────────────────────────
# Cancel
# ──────────────────────────────────────────────

async def cancel(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    context.user_data.clear()
    await update.message.reply_text("Cancelled.", reply_markup=ReplyKeyboardRemove())
    return ConversationHandler.END


# ──────────────────────────────────────────────
# App builder
# ──────────────────────────────────────────────

def build_application() -> Application:
    app = ApplicationBuilder().token(BOT_TOKEN).build()

    conv_handler = ConversationHandler(
        entry_points=[CommandHandler("split", split_start)],
        states={
            CHOICE:        [MessageHandler(filters.TEXT & ~filters.COMMAND, choose_split_type)],
            TOTAL:         [MessageHandler(filters.TEXT & ~filters.COMMAND, get_total)],
            PEOPLE_EQUAL:  [MessageHandler(filters.TEXT & ~filters.COMMAND, get_people_equal)],
            PEOPLE_INDIV:  [MessageHandler(filters.TEXT & ~filters.COMMAND, get_people_individual)],
            NAME_INDIV:    [MessageHandler(filters.TEXT & ~filters.COMMAND, get_name_individual)],
            ITEM_COUNT:    [MessageHandler(filters.TEXT & ~filters.COMMAND, get_item_count)],
            ITEM_AMOUNT:   [MessageHandler(filters.TEXT & ~filters.COMMAND, get_individual_amount)],
            GST_INDIV:     [MessageHandler(filters.TEXT & ~filters.COMMAND, get_gst_individual)],
            SERVICE_INDIV: [MessageHandler(filters.TEXT & ~filters.COMMAND, get_service_individual)],
        },
        fallbacks=[CommandHandler("cancel", cancel)],
    )

    app.add_handler(CommandHandler("start", start))
    app.add_handler(conv_handler)
    return app